### ISSUE TITLE
Cannot read property 'clientId' of undefined

### ISSUE THREAD

**Issue by CharlieHess** [samiskin/redux-electron-store#17]
Saw this crash after an upgrade to 0.3.6, I suspect [the source names PR](https://github.com/samiskin/redux-electron-store/commit/d2e9ab2c6fdede530edea5d3d7ab576a26548d64). Here's a log from Slack, with the context around it. We closed a window and the crash occurred in the first dispatch after that; perhaps the enhancer is holding a reference?

```
2016-04-13T01:12:08.101Z - info: Display changed! Recreating notifications window
2016-04-13T01:12:08.269Z - info: Notifications window closed, disposing
2016-04-13T01:12:08.335Z - info: REMOVE_WINDOW : 2
2016-04-13T01:12:08.918Z - info: Creating notifications window
2016-04-13T01:12:09.079Z - info: ADD_WINDOW : {
  "windowId": 9,
  "windowType": "NOTIFICATIONS"
}
2016-04-13T01:12:21.824Z - info: FOCUS_PRIMARY_TEAM 
2016-04-13T01:12:33.632Z - error: **** ABOUT TO CRASH ****
2016-04-13T01:12:33.637Z - error: Cannot read property 'clientId' of undefined
2016-04-13T01:12:33.652Z - error: TypeError: Cannot read property 'clientId' of undefined
  at EventEmitter.<anonymous> (C:\Users\mariab\AppData\Local\slack\app-2.0.4-beta1\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:104:49)
  at emitTwo (events.js:100:13)
  at EventEmitter.emit (events.js:185:7)
  at EventEmitter.<anonymous> (C:\Users\mariab\AppData\Local\slack\app-2.0.4-beta1\resources\electron.asar\browser\api\web-contents.js:128:25)
  at emitTwo (events.js:100:13)
  at EventEmitter.emit (events.js:185:7)
```

**Comment by samiskin** [comment]
Should be fixed in v0.3.7 :+1:
